#ifndef _CONFIGURATION_H
#define _CONFIGURATION_H

#define DEBOUNCE_PERIOD		200
#define SYNC_PERIOD			60000L
#define MAX_PRODUCT_COUNT    4
#define PRODUCT_NAME_SIZE    19
#define CATALOG_HEADER_SIZE  21

#endif